#!/usr/bin/env bash
#
# Build MsgDots.app into ./dist/.
#
# Usage:  ./build.sh            # universal binary (arm64 + x86_64), release config
#         ./build.sh --arm64    # arm64-only, faster local iteration
#         ./build.sh --debug    # debug config (skips -O, keeps asserts)
#
# Produces: ./dist/MsgDots.app  (fully self-contained, ~2-4 MB)
#

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

# --- parse flags ------------------------------------------------------------
CONFIG="release"
ARCH_MODE="universal"
for arg in "$@"; do
    case "$arg" in
        --debug)     CONFIG="debug"     ;;
        --release)   CONFIG="release"   ;;
        --arm64)     ARCH_MODE="arm64"  ;;
        --x86_64)    ARCH_MODE="x86_64" ;;
        --universal) ARCH_MODE="universal" ;;
        *) echo "unknown arg: $arg" >&2; exit 2 ;;
    esac
done

# --- swift build ------------------------------------------------------------
SWIFT_FLAGS=(-c "$CONFIG")
case "$ARCH_MODE" in
    universal) SWIFT_FLAGS+=(--arch arm64 --arch x86_64) ;;
    arm64)     SWIFT_FLAGS+=(--arch arm64)  ;;
    x86_64)    SWIFT_FLAGS+=(--arch x86_64) ;;
esac

echo "==> swift build ${SWIFT_FLAGS[*]}"
swift build "${SWIFT_FLAGS[@]}"

# swift build puts the binary in different places depending on arch mode:
#   single-arch:  .build/<config>/MsgDots
#   universal:    .build/apple/Products/<Config capitalised>/MsgDots
if [[ "$ARCH_MODE" == "universal" ]]; then
    CONFIG_TITLE="$(tr '[:lower:]' '[:upper:]' <<<"${CONFIG:0:1}")${CONFIG:1}"
    BIN="${HERE}/.build/apple/Products/${CONFIG_TITLE}/MsgDots"
else
    BIN="${HERE}/.build/${CONFIG}/MsgDots"
fi

if [[ ! -x "$BIN" ]]; then
    echo "error: built binary not found at $BIN" >&2
    exit 3
fi

# --- assemble .app bundle ---------------------------------------------------
APP="${HERE}/dist/MsgDots.app"
rm -rf "$APP"
mkdir -p "${APP}/Contents/MacOS"
mkdir -p "${APP}/Contents/Resources"

cp "$BIN" "${APP}/Contents/MacOS/MsgDots"
cp "${HERE}/Resources/Info.plist" "${APP}/Contents/Info.plist"

# App icon -- generated by scripts/make-icns.sh.  Auto-generate on first build.
if [[ ! -f "${HERE}/Resources/AppIcon.icns" ]]; then
    echo "==> AppIcon.icns missing, generating"
    "${HERE}/scripts/make-icns.sh"
fi
cp "${HERE}/Resources/AppIcon.icns" "${APP}/Contents/Resources/AppIcon.icns"

# Ad-hoc code-sign. Without a Developer ID the system treats each build as a
# distinct app; signing avoids "damaged app" Gatekeeper errors.
codesign --force --deep --sign - "$APP" 2>/dev/null || true

# Strip quarantine bit so Gatekeeper does not block first launch.
xattr -cr "$APP" || true

APP_SIZE=$(du -sh "$APP" | awk '{print $1}')
echo ""
echo "built: $APP  (${APP_SIZE})"
echo ""
echo "NOTE: after every rebuild TCC permissions reset. If permissions stop working:"
echo "      tccutil reset All com.msgdots.app"
echo "      then relaunch MsgDots and grant permissions in the panel."
echo ""
echo "Required permissions (first launch triggers prompts automatically):"
echo "  - System Settings > Privacy > Input Monitoring  -> allow MsgDots"
echo "  - System Settings > Privacy > Accessibility     -> allow MsgDots"
echo "  - System Settings > Privacy > Screen Recording  -> allow MsgDots"
echo "  - System Settings > Privacy > Automation        -> MsgDots > WeChat"
